Application:
    ID                      :   'VL-001'
    Name                    :   'Voice Learning Demo'
    LogSetup:
        Log_Dir             :   'Log'           #Directory Name for Logging, Log files will be stored under this location
        Log_Name            :   'Application_Log'
        Log_Level           :   'DEBUG'         
    DataSource:
        In_Cloud            :   'Azure'         #Possible Data Source Locations, Local or any cloud location - 'Azure','AWS','Google'
        In_Dir              :   'Data'           #Directory path for files, specify absolute path for local file and directory path for blobs like 'Data/File1/'
        Azure_Container     :   'XXXX'
        Out_Cloud           :   'Local'         #Possible Data Source Locations, Local or any cloud location - 'Azure','AWS','Google'
        Out_Dir             :   'outputs'           #Directory path for output
        Model_Dir           :   'outputs'           #Saved Models directory       
    LSTM:
        max_features        :   100000
        maxlen              :   200
        vector_length       :   64
        batch_size          :   128
        epochs              :   10
    Speech_Subscription:
        YOUR_API_KEY        :   'XXXX'
        REGION              :   'XXXX'           # westus, eastasia, northeurope 
        MODE                :   'interactive'
        LANG                :   'en-US'
        FORMAT              :   'simple'
    Cloud_Storage:
        Storage_Account     :   'XXX'                                                                              #Storage Container Name
        Storage_Key         :   'XXXX'      # Key to access blobs in the storage account
    Model:
        LSTM_model_weight   :   'imdb_bidirectional_lstm.hdf5'
        LSTM_model_json     :   'imdb_bidirectional_lstm.json'
        LDA_model           :   'LDA_Topic_Model.pkl'
